48062_Initial_API
awesome-academy/Marvel_App_01 pull request #5
Opened 2022-04-12 02:44 UTC by datlt-2996

## [Pull request title]
48062_Initial_API

### [Redmine link]
https://edu-redmine.sun-asterisk.vn/issues/48062
#### Screenshots (nếu có)

2022-04-12 02:59 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Constants/PrivateConstants.swift
> +let publicKey = "3bc8f50b5e50a13f6ed641dd3e8a0a9a" //"developer.marvel.com public key"
hide api key

2022-04-12 02:59 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Extensions/CodeableExtension.swift
> +        }.resume()
xoá cmt
Nên tách ra thành 1 class

2022-04-12 02:59 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    private let baseURL = "https://gateway.marvel.com"
quản lý url vào 1 component

2022-04-12 02:59 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        // https://gateway.marvel.com/v1/public/characters/1011334/comics
xoá cmt

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Extensions/CodeableExtension.swift
> +            if let data = data, statusCode >= 200 && statusCode < 300{
```suggestion
            if let data = data, 200...299 ~= statusCode {
```

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Models/CharaterModels/CharacterBaseData.swift
> +
remove blank

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    private func buildHashToken(timestamp: TimeInterval) -> String{
mấy cái khác e cũng sửa lại như này nhé
```suggestion
    private func buildHashToken(timestamp: TimeInterval) -> String {
```

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    private func buildQueryString(pageNumber: Int = 0, isCharacterList: Bool = false) -> String{
```suggestion
    private func buildQueryString(pageNumber: Int = 0, isCharacterList: Bool = false) -> String {
```

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        let request = URLRequest(url: URL(string: url)!)
k force unwrap dùng `guard let`

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        let request = URLRequest(url: URL(string: url)!)
tương tự

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        print(url)
remove

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Models/CharaterModels/CharacterBaseData.swift
> +struct CharacterBaseData: Codable {
```suggestion
import Foundation

struct CharacterBaseData: Codable {
```

2022-04-12 03:18 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Hash/Hash.swift
> +func MD5(str: String) -> String {
tạo 1 cái class để quản lý e

2022-04-12 06:49 UTC, dong-dg reviewed
Còn nhiều lỗi coding convention liên quan break line, em check lại nhé

2022-04-12 06:49 UTC, dong-dg commented on .swiftlint.yml
> +    warning: 200
warning em để về 120 nhé

2022-04-12 06:49 UTC, dong-dg commented on MarvelApp/MarvelApp/Constants/Constants.swift
> +struct Constants {
```suggestion
import Foundation

struct Constants {
```

2022-04-12 06:49 UTC, dong-dg commented on MarvelApp/MarvelApp/Models/CharaterModels/Character.swift
> +    let id: Int?
id không bao giờ đc nil

2022-04-12 06:49 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/ComicModels/ComicBaseData.swift
> +    enum CodingKeys: String, CodingKey {
tương tự

2022-04-12 06:49 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/ComicModels/ComicBookDataSource.swift
> +    enum CodingKeys: String, CodingKey {
tương tự

2022-04-12 06:49 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/ComicModels/Comic.swift
> +    }
```suggestion
    let fallbackCover: [Thumbnail]?
    
    enum CodingKeys: String, CodingKey {
        case cover = "thumbnail", fallbackCover = "images", id
        case issueNumber, pageCount, title, description
    }
```

2022-04-12 06:49 UTC, namtn-2711 commented on MarvelApp/MarvelApp/key.plist
> +</plist>
add vào file git .ignore

2022-04-12 11:58 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Extensions/CodeableExtension.swift
> +    }
tách thành class API đi em

2022-04-12 11:58 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    func getComics(id: Int) -> URLRequest? {
```suggestion
    }
    
    func getComics(id: Int) -> URLRequest? {
```

2022-04-12 11:58 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    private func buildQueryString(pageNumber: Int = 0, isCharacterList: Bool = false) -> String {
```suggestion
    }
    
    private func buildQueryString(pageNumber: Int = 0, isCharacterList: Bool = false) -> String {
```

2022-04-12 11:58 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    private func buildHashToken(timestamp: TimeInterval) -> String {
```suggestion
    }
    
    private func buildHashToken(timestamp: TimeInterval) -> String {
```

2022-04-12 11:58 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Hash/Hash.swift
> +func MD5(str: String) -> String {
@datlt-2996 Chưa fix sao đã resolve r em ?

2022-04-12 12:04 UTC, datlt-2996 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    private func buildHashToken(timestamp: TimeInterval) -> String {
Cái này build lên nó bị warning do e cài swiftlint ạ

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Hash/Hash.swift
> +}
tạo 1 folder `Extensions` rồi bên trong tạo 1 file `String+` move đoạn code này vào e

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        _ = URLRequest(url: url)
`_ = URLRequest(url: url)` remove đi e

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        _ = URLRequest(url: url)
tương tự

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        guard let url = URL(string: url) else { return nil}
```suggestion
        guard let url = URL(string: url) else { return nil }
```

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        guard let url = URL(string: url) else { return nil}
```suggestion
        guard let url = URL(string: url) else { return nil }
```

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Hash/Hash.swift
> +       if let strData = str.data(using: String.Encoding.utf8) {
```suggestion
    func encodeMD5() -> String {
       if let strData = self.data(using: String.Encoding.utf8) {
```

2022-04-12 14:57 UTC, phonglh-2668 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        return String().MD5(str: unhashedString)
```suggestion
        return unhashedString. encodeMD5()
```

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/CharaterModels/CharacterBaseData.swift
> +    enum CodingKeys: String, CodingKey {
```suggestion
    let apiDataSource: CharacterDataSource?
    
    enum CodingKeys: String, CodingKey {
```

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/CharaterModels/CharacterDataSource.swift
> +    enum CodingKeys: String, CodingKey {
.

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/CharaterModels/CharacterDataSource.swift
> +    init(from decoder: Decoder) throws {
.

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/CharaterModels/CharacterDataSource.swift
> +    func encode(to encoder: Encoder) throws {
.

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Models/ComicModels/Comic.swift
> +    enum CodingKeys: String, CodingKey {
.

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/API.swift
> +    func decoderWithRequest<T: Decodable> (
```suggestion
    static let shared = APICaller()
    
    private init() {
        print("APICaller Singleton initialized!")
    }
    
    func request<T: Decodable> (
```

2022-04-13 01:26 UTC, namtn-2711 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    func getCharacters(pageNumber: Int = 0) -> URLRequest? {
.

2022-04-13 01:26 UTC, daolq-2712 requested changes
Pls check my comments!

2022-04-13 01:26 UTC, daolq-2712 commented on .gitignore
> +key.plist
add a blank line at end of this file

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Models/ComicModels/Comic.swift
> +    init(from decoder: Decoder) throws {
add a blank line between declare `the variable` and `func`

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/API.swift
> +    func decoderWithRequest<T: Decodable> (
add a blank line a bove this line!

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/API.swift
> +        fromURLRequest urlRequest: URLRequest ,
```suggestion
        fromURLRequest urlRequest: URLRequest,
```

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +        print(url)
remove log!

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    func getCharacters(pageNumber: Int = 0) -> URLRequest? {
```suggestion
    func getCharactersURLRequest(pageNumber: Int = 0) -> URLRequest? {
```

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/RequestHandler.swift
> +    func getComics(id: Int) -> URLRequest? {
```suggestion
    func getComicsURLRequest(id: Int) -> URLRequest? {
```

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/String+.swift
> +extension String {
move this file to folder `rootProject/Extensions`

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Networking/API.swift
> +class APICaller {
```suggestion
class API {
```
The name of Class should be the same as the name of file that contains it

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Models/ComicModels/ComicBaseData.swift
> +struct ComicBaseData: Codable {
move to folder `Networking/data`

2022-04-13 01:26 UTC, daolq-2712 commented on MarvelApp/MarvelApp/Models/ComicModels/ComicBaseData.swift
> +    let apiDataSource: ComicBookDataSource?
Use Generic type for this variable to reduce duplicate code!

ref: https://www.swiftbysundell.com/articles/creating-generic-networking-apis-in-swift/

2022-04-13 04:17 UTC, daolq-2712 approved these changes

2022-04-13 04:25 UTC, namtn-2711 reviewed
Ok!

2022-04-13 04:25 UTC, merged